`tidystats` offers a piping API similar to `magittr` in R using `>>`

Importing from `pymer4.tidystats.pipe` instead of `pymer4.tidystats` will enable this functionality.  
Numerous `polars` DataFrame methods are also available for use in pipes

In [6]:
import pymer4.tidystats.pipe as ts

from pymer4.tidystats import load_dataset
from polars import col
sleep = load_dataset('sleep')

In [5]:
# Fit a regression and get the first 5 predicted values
(
    sleep
    >> ts.lm("Reaction ~ Days")
    >> ts.augment()
    >> ts.select("Reaction", "fitted")
    >> ts.head()
)

shape: (5, 2)
┌──────────┬────────────┐
│ Reaction ┆ fitted     │
│ ---      ┆ ---        │
│ f64      ┆ f64        │
╞══════════╪════════════╡
│ 249.56   ┆ 251.405105 │
│ 258.7047 ┆ 261.872391 │
│ 250.8006 ┆ 272.339677 │
│ 321.4398 ┆ 282.806963 │
│ 356.8519 ┆ 293.274249 │
└──────────┴────────────┘

In [8]:
# Inspect the model fit for a regression using data from days > 1 only
(
    sleep
    >> ts.filter(col('Days') > 1)
    >> ts.lm('Days ~ 1')
    >> ts.glance()
    >> ts.select('r_squared', 'AIC', 'logLik')
)

shape: (1, 3)
┌───────────┬────────────┬────────────┐
│ r_squared ┆ AIC        ┆ logLik     │
│ ---       ┆ ---        ┆ ---        │
│ f64       ┆ f64        ┆ f64        │
╞═══════════╪════════════╪════════════╡
│ 0.0       ┆ 651.439141 ┆ -323.71957 │
└───────────┴────────────┴────────────┘

In [10]:
# Fit an LMM and look at the fixed effect estimate only
(
    sleep
    >> ts.lmer('Days ~ 1 + (1 | Subject)')
    >> ts.tidy()
    >> ts.filter(col('effect') == 'fixed')
)

R[write to console]: boundary (singular) fit: see help('isSingular')

shape: (1, 8)
┌────────┬───────┬─────────────┬──────────┬───────────┬───────────┬───────┬────────────┐
│ effect ┆ group ┆ term        ┆ estimate ┆ std_error ┆ statistic ┆ df    ┆ p_value    │
│ ---    ┆ ---   ┆ ---         ┆ ---      ┆ ---       ┆ ---       ┆ ---   ┆ ---        │
│ str    ┆ str   ┆ str         ┆ f64      ┆ f64       ┆ f64       ┆ f64   ┆ f64        │
╞════════╪═══════╪═════════════╪══════════╪═══════════╪═══════════╪═══════╪════════════╡
│ fixed  ┆ null  ┆ (Intercept) ┆ 4.5      ┆ 0.214684  ┆ 20.961003 ┆ 179.0 ┆ 4.5937e-50 │
└────────┴───────┴─────────────┴──────────┴───────────┴───────────┴───────┴────────────┘